# Generated by Django 4.1.3 on 2022-11-30 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0002_agenda_alumno_asignatura_asistencia_forma_pago_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Administrador",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=50)),
                ("fechacreacion", models.DateTimeField(auto_now_add=True)),
                ("clave", models.CharField(max_length=10)),
            ],
        ),
    ]
